### PR TITLE
Fix #22 

### LINKED ISSUE #22: File update Error
Sometimes, the goblin_db.json gets corrupted on update. This happens when there is data in the file (i.e. last execution stored stuff) and open again the database. On doing a .set, it store it as a new json at the end of the actual one, instead of load the previous data, add the new value, and store it all together.

I'm now trying to create some code snippet to reproduce it, but the ressult is this:
```json
{"User_5":{"name":"Paco","id":5}}"User_8":{"name":"Paco","id":8}}
```
instead of this:
```json
{"User_5":{"name":"Paco","id":5},"User_8":{"name":"Paco","id":8}}
```

### PR DESCRIPTION
**Pull request by CodingCarlos**
Replicate Ambush flush before write on change.

### CODE REVIEW

**Comment by CodingCarlos** [comment]
Just last commit matters. 

I've done a merge from master before @UlisesGascon merge #23, so I've merged back the origin dev branch before doing stuff.

**Comment by UlisesGascon** [comment]
Thanks @CodingCarlos ! Did you pass the test, too?

**Comment by CodingCarlos** [comment]
All tests are passing well, yes.

_we shall fix the .travis file, to make this automatically... _

**Comment by UlisesGascon** [comment]
I agree... I will create an issue about it!

**Pull request merged**
